### ISSUE TITLE
Custom Progress Bar

### ISSUE THREAD

**Issue by 1ambda** [oh-my-github/viewer-default#9]
Since bootstrap progress bar doesn't support multiple colors, we should implement custom progress bars. 
- http://cssdeck.com/labs/twitter-bootstrap-progress-bars
- http://bootstrapdesigntools.com/tools/bootstrap-progress-bar-designer/
- http://bootsnipp.com/snippets/featured/flat-color-progress-bars

**Comment by SehoNoh** [comment]
I recommend this theme. because I'm lovin it.

http://designmodo.github.io/Flat-UI/

**Comment by 1ambda** [comment]
Progress bar examples:

<img width="543" alt="screen shot 2016-02-08 at 4 50 01 pm" src="https://cloud.githubusercontent.com/assets/4968473/12880446/0fcc12aa-ce84-11e5-97dd-5392843de80b.png">
